# Generated by Django 3.1.7 on 2021-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('General Surgeon', 'General Surgeon'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology')], max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor_table',
            },
        ),
    ]
