# Generated by Django 3.1.7 on 2021-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
