# Generated by Django 3.1.7 on 2021-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210506_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pdate', models.CharField(max_length=100)),
                ('ptime', models.CharField(choices=[('8:00 to 9:00', '8:00 to 9:00'), ('9:00 to 10:00', '9:00 to 10:00'), ('10:00 to 1:00', '10:00 to 1:00')], max_length=100)),
                ('specialization', models.CharField(choices=[('General Surgeon', 'General Surgeon'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology')], max_length=100)),
            ],
            options={
                'db_table': 'appointment_table',
            },
        ),
    ]
