# Generated by Django 3.1.7 on 2021-05-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='docuname',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
