# Generated by Django 3.1.7 on 2021-05-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_appointment_docuname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.CharField(default='chandu2811', max_length=100),
        ),
    ]
