# Generated by Django 3.1.7 on 2021-05-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('medicationname', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('attachment', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('file_category', models.CharField(choices=[('Prescription', 'Prescription'), ('Diagonisis Reports', 'Diagonisis Reports'), ('Others', 'Others')], max_length=50)),
                ('fileuploadtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_table',
            },
        ),
    ]
