# Generated by Django 3.1.7 on 2021-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('patientnname', models.CharField(max_length=100)),
                ('assistname', models.CharField(max_length=100)),
                ('requiremets', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=255)),
                ('fileuploadtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lifebank_table',
            },
        ),
        migrations.AlterField(
            model_name='medication',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
