# Generated by Django 3.1.7 on 2021-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210517_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifebank',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
