# Generated by Django 3.1.7 on 2021-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_lifebank_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='disease',
            field=models.TextField(default='Fever', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='type_category',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Minor', max_length=50),
        ),
    ]
