# Generated by Django 3.1.7 on 2021-05-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210518_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='type_category',
        ),
    ]
