# Generated by Django 3.1.7 on 2021-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_medication_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='type_category',
            field=models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], default='Minor', max_length=50),
        ),
    ]
