# Generated by Django 3.1.7 on 2021-05-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_medication_type_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='file_name',
        ),
    ]
