# Generated by Django 3.1.7 on 2021-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_medication_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='patientname',
            field=models.CharField(default='Sai', max_length=100),
        ),
    ]
