# Generated by Django 3.1.7 on 2021-04-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_usersregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersregistration',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
